import { Provider } from "../types";

export const providers: Provider[] = [
  {
    id: "1",
    name: "Dr. Sarah Mitchell",
    specialty: "general",
    city: "New York",
    country: "USA",
    rating: 4.9,
    verified: true,
  },
  {
    id: "2",
    name: "Dr. James Chen",
    specialty: "neurology",
    city: "San Francisco",
    country: "USA",
    rating: 4.8,
    verified: true,
  },
  {
    id: "3",
    name: "Dr. Emily Carter",
    specialty: "cardiology",
    city: "Chicago",
    country: "USA",
    rating: 4.7,
    verified: true,
  },
  {
    id: "4",
    name: "Dr. Michael Brown",
    specialty: "orthopedics",
    city: "Los Angeles",
    country: "USA",
    rating: 4.6,
    verified: false,
  },
  {
    id: "5",
    name: "Dr. Anna Williams",
    specialty: "pediatrics",
    city: "Boston",
    country: "USA",
    rating: 4.9,
    verified: true,
  },
  {
    id: "6",
    name: "Dr. David Kim",
    specialty: "dermatology",
    city: "Seattle",
    country: "USA",
    rating: 4.5,
    verified: true,
  },
];
